/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QaRouteImport } from './routes/qa'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as QuizMyAttemptsRouteImport } from './routes/quiz.my-attempts'
import { Route as QuizLeaderboardRouteImport } from './routes/quiz.leaderboard'
import { Route as QuizBookmarksRouteImport } from './routes/quiz.bookmarks'
import { Route as QuizCategoryRouteImport } from './routes/quiz.$category'
import { Route as QaLeaderboardRouteImport } from './routes/qa.leaderboard'
import { Route as QaAskRouteImport } from './routes/qa.ask'
import { Route as QaQuestionIdRouteImport } from './routes/qa.$questionId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as QuizReviewAttemptIdRouteImport } from './routes/quiz.review.$attemptId'
import { Route as QuizPlayQuizIdRouteImport } from './routes/quiz.play.$quizId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTournamentsRouteImport } from './routes/_authenticated/admin.tournaments'
import { Route as AuthenticatedAdminQuizIndexRouteImport } from './routes/_authenticated/admin.quiz.index'
import { Route as ApiPublicHooksDispatchRemindersRouteImport } from './routes/api/public/hooks/dispatch-reminders'
import { Route as AuthenticatedAdminQuizCategoriesRouteImport } from './routes/_authenticated/admin.quiz.categories'
import { Route as AuthenticatedAdminQuizAttemptsRouteImport } from './routes/_authenticated/admin.quiz.attempts'
import { Route as AuthenticatedAdminQuizQuizIdRouteImport } from './routes/_authenticated/admin.quiz.$quizId'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizMyAttemptsRoute = QuizMyAttemptsRouteImport.update({
  id: '/quiz/my-attempts',
  path: '/quiz/my-attempts',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizLeaderboardRoute = QuizLeaderboardRouteImport.update({
  id: '/quiz/leaderboard',
  path: '/quiz/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizBookmarksRoute = QuizBookmarksRouteImport.update({
  id: '/quiz/bookmarks',
  path: '/quiz/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryRoute = QuizCategoryRouteImport.update({
  id: '/quiz/$category',
  path: '/quiz/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const QaLeaderboardRoute = QaLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => QaRoute,
} as any)
const QaAskRoute = QaAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => QaRoute,
} as any)
const QaQuestionIdRoute = QaQuestionIdRouteImport.update({
  id: '/$questionId',
  path: '/$questionId',
  getParentRoute: () => QaRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const QuizReviewAttemptIdRoute = QuizReviewAttemptIdRouteImport.update({
  id: '/quiz/review/$attemptId',
  path: '/quiz/review/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPlayQuizIdRoute = QuizPlayQuizIdRouteImport.update({
  id: '/quiz/play/$quizId',
  path: '/quiz/play/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTournamentsRoute =
  AuthenticatedAdminTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuizIndexRoute =
  AuthenticatedAdminQuizIndexRouteImport.update({
    id: '/quiz/',
    path: '/quiz/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksDispatchRemindersRoute =
  ApiPublicHooksDispatchRemindersRouteImport.update({
    id: '/api/public/hooks/dispatch-reminders',
    path: '/api/public/hooks/dispatch-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminQuizCategoriesRoute =
  AuthenticatedAdminQuizCategoriesRouteImport.update({
    id: '/quiz/categories',
    path: '/quiz/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuizAttemptsRoute =
  AuthenticatedAdminQuizAttemptsRouteImport.update({
    id: '/quiz/attempts',
    path: '/quiz/attempts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuizQuizIdRoute =
  AuthenticatedAdminQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/qa': typeof QaRouteWithChildren
  '/signup': typeof SignupRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/qa/$questionId': typeof QaQuestionIdRoute
  '/qa/ask': typeof QaAskRoute
  '/qa/leaderboard': typeof QaLeaderboardRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/bookmarks': typeof QuizBookmarksRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/my-attempts': typeof QuizMyAttemptsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/quiz/': typeof QuizIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/quiz/review/$attemptId': typeof QuizReviewAttemptIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/quiz/$quizId': typeof AuthenticatedAdminQuizQuizIdRoute
  '/admin/quiz/attempts': typeof AuthenticatedAdminQuizAttemptsRoute
  '/admin/quiz/categories': typeof AuthenticatedAdminQuizCategoriesRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/admin/quiz/': typeof AuthenticatedAdminQuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/qa': typeof QaRouteWithChildren
  '/signup': typeof SignupRoute
  '/videos': typeof VideosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qa/$questionId': typeof QaQuestionIdRoute
  '/qa/ask': typeof QaAskRoute
  '/qa/leaderboard': typeof QaLeaderboardRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/bookmarks': typeof QuizBookmarksRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/my-attempts': typeof QuizMyAttemptsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/quiz': typeof QuizIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/quiz/review/$attemptId': typeof QuizReviewAttemptIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/quiz/$quizId': typeof AuthenticatedAdminQuizQuizIdRoute
  '/admin/quiz/attempts': typeof AuthenticatedAdminQuizAttemptsRoute
  '/admin/quiz/categories': typeof AuthenticatedAdminQuizCategoriesRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/admin/quiz': typeof AuthenticatedAdminQuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRoute
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/qa': typeof QaRouteWithChildren
  '/signup': typeof SignupRoute
  '/videos': typeof VideosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/qa/$questionId': typeof QaQuestionIdRoute
  '/qa/ask': typeof QaAskRoute
  '/qa/leaderboard': typeof QaLeaderboardRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/bookmarks': typeof QuizBookmarksRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/my-attempts': typeof QuizMyAttemptsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/quiz/': typeof QuizIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/_authenticated/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/quiz/review/$attemptId': typeof QuizReviewAttemptIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/quiz/$quizId': typeof AuthenticatedAdminQuizQuizIdRoute
  '/_authenticated/admin/quiz/attempts': typeof AuthenticatedAdminQuizAttemptsRoute
  '/_authenticated/admin/quiz/categories': typeof AuthenticatedAdminQuizCategoriesRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/_authenticated/admin/quiz/': typeof AuthenticatedAdminQuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/events'
    | '/library'
    | '/login'
    | '/notices'
    | '/qa'
    | '/signup'
    | '/videos'
    | '/admin'
    | '/profile'
    | '/qa/$questionId'
    | '/qa/ask'
    | '/qa/leaderboard'
    | '/quiz/$category'
    | '/quiz/bookmarks'
    | '/quiz/leaderboard'
    | '/quiz/my-attempts'
    | '/tournaments/$id'
    | '/quiz/'
    | '/tournaments/'
    | '/admin/tournaments'
    | '/admin/users'
    | '/quiz/play/$quizId'
    | '/quiz/review/$attemptId'
    | '/admin/'
    | '/admin/quiz/$quizId'
    | '/admin/quiz/attempts'
    | '/admin/quiz/categories'
    | '/api/public/hooks/dispatch-reminders'
    | '/admin/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/events'
    | '/library'
    | '/login'
    | '/notices'
    | '/qa'
    | '/signup'
    | '/videos'
    | '/profile'
    | '/qa/$questionId'
    | '/qa/ask'
    | '/qa/leaderboard'
    | '/quiz/$category'
    | '/quiz/bookmarks'
    | '/quiz/leaderboard'
    | '/quiz/my-attempts'
    | '/tournaments/$id'
    | '/quiz'
    | '/tournaments'
    | '/admin/tournaments'
    | '/admin/users'
    | '/quiz/play/$quizId'
    | '/quiz/review/$attemptId'
    | '/admin'
    | '/admin/quiz/$quizId'
    | '/admin/quiz/attempts'
    | '/admin/quiz/categories'
    | '/api/public/hooks/dispatch-reminders'
    | '/admin/quiz'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/events'
    | '/library'
    | '/login'
    | '/notices'
    | '/qa'
    | '/signup'
    | '/videos'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/qa/$questionId'
    | '/qa/ask'
    | '/qa/leaderboard'
    | '/quiz/$category'
    | '/quiz/bookmarks'
    | '/quiz/leaderboard'
    | '/quiz/my-attempts'
    | '/tournaments/$id'
    | '/quiz/'
    | '/tournaments/'
    | '/_authenticated/admin/tournaments'
    | '/_authenticated/admin/users'
    | '/quiz/play/$quizId'
    | '/quiz/review/$attemptId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/quiz/$quizId'
    | '/_authenticated/admin/quiz/attempts'
    | '/_authenticated/admin/quiz/categories'
    | '/api/public/hooks/dispatch-reminders'
    | '/_authenticated/admin/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRoute
  EventsRoute: typeof EventsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  QaRoute: typeof QaRouteWithChildren
  SignupRoute: typeof SignupRoute
  VideosRoute: typeof VideosRoute
  QuizCategoryRoute: typeof QuizCategoryRoute
  QuizBookmarksRoute: typeof QuizBookmarksRoute
  QuizLeaderboardRoute: typeof QuizLeaderboardRoute
  QuizMyAttemptsRoute: typeof QuizMyAttemptsRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  QuizIndexRoute: typeof QuizIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  QuizPlayQuizIdRoute: typeof QuizPlayQuizIdRoute
  QuizReviewAttemptIdRoute: typeof QuizReviewAttemptIdRoute
  ApiPublicHooksDispatchRemindersRoute: typeof ApiPublicHooksDispatchRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/my-attempts': {
      id: '/quiz/my-attempts'
      path: '/quiz/my-attempts'
      fullPath: '/quiz/my-attempts'
      preLoaderRoute: typeof QuizMyAttemptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/leaderboard': {
      id: '/quiz/leaderboard'
      path: '/quiz/leaderboard'
      fullPath: '/quiz/leaderboard'
      preLoaderRoute: typeof QuizLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/bookmarks': {
      id: '/quiz/bookmarks'
      path: '/quiz/bookmarks'
      fullPath: '/quiz/bookmarks'
      preLoaderRoute: typeof QuizBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$category': {
      id: '/quiz/$category'
      path: '/quiz/$category'
      fullPath: '/quiz/$category'
      preLoaderRoute: typeof QuizCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/leaderboard': {
      id: '/qa/leaderboard'
      path: '/leaderboard'
      fullPath: '/qa/leaderboard'
      preLoaderRoute: typeof QaLeaderboardRouteImport
      parentRoute: typeof QaRoute
    }
    '/qa/ask': {
      id: '/qa/ask'
      path: '/ask'
      fullPath: '/qa/ask'
      preLoaderRoute: typeof QaAskRouteImport
      parentRoute: typeof QaRoute
    }
    '/qa/$questionId': {
      id: '/qa/$questionId'
      path: '/$questionId'
      fullPath: '/qa/$questionId'
      preLoaderRoute: typeof QaQuestionIdRouteImport
      parentRoute: typeof QaRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/quiz/review/$attemptId': {
      id: '/quiz/review/$attemptId'
      path: '/quiz/review/$attemptId'
      fullPath: '/quiz/review/$attemptId'
      preLoaderRoute: typeof QuizReviewAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/play/$quizId': {
      id: '/quiz/play/$quizId'
      path: '/quiz/play/$quizId'
      fullPath: '/quiz/play/$quizId'
      preLoaderRoute: typeof QuizPlayQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tournaments': {
      id: '/_authenticated/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz/': {
      id: '/_authenticated/admin/quiz/'
      path: '/quiz'
      fullPath: '/admin/quiz/'
      preLoaderRoute: typeof AuthenticatedAdminQuizIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/dispatch-reminders': {
      id: '/api/public/hooks/dispatch-reminders'
      path: '/api/public/hooks/dispatch-reminders'
      fullPath: '/api/public/hooks/dispatch-reminders'
      preLoaderRoute: typeof ApiPublicHooksDispatchRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/quiz/categories': {
      id: '/_authenticated/admin/quiz/categories'
      path: '/quiz/categories'
      fullPath: '/admin/quiz/categories'
      preLoaderRoute: typeof AuthenticatedAdminQuizCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz/attempts': {
      id: '/_authenticated/admin/quiz/attempts'
      path: '/quiz/attempts'
      fullPath: '/admin/quiz/attempts'
      preLoaderRoute: typeof AuthenticatedAdminQuizAttemptsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz/$quizId': {
      id: '/_authenticated/admin/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/admin/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedAdminQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminTournamentsRoute: typeof AuthenticatedAdminTournamentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminQuizQuizIdRoute: typeof AuthenticatedAdminQuizQuizIdRoute
  AuthenticatedAdminQuizAttemptsRoute: typeof AuthenticatedAdminQuizAttemptsRoute
  AuthenticatedAdminQuizCategoriesRoute: typeof AuthenticatedAdminQuizCategoriesRoute
  AuthenticatedAdminQuizIndexRoute: typeof AuthenticatedAdminQuizIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminTournamentsRoute: AuthenticatedAdminTournamentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminQuizQuizIdRoute: AuthenticatedAdminQuizQuizIdRoute,
  AuthenticatedAdminQuizAttemptsRoute: AuthenticatedAdminQuizAttemptsRoute,
  AuthenticatedAdminQuizCategoriesRoute: AuthenticatedAdminQuizCategoriesRoute,
  AuthenticatedAdminQuizIndexRoute: AuthenticatedAdminQuizIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface QaRouteChildren {
  QaQuestionIdRoute: typeof QaQuestionIdRoute
  QaAskRoute: typeof QaAskRoute
  QaLeaderboardRoute: typeof QaLeaderboardRoute
}

const QaRouteChildren: QaRouteChildren = {
  QaQuestionIdRoute: QaQuestionIdRoute,
  QaAskRoute: QaAskRoute,
  QaLeaderboardRoute: QaLeaderboardRoute,
}

const QaRouteWithChildren = QaRoute._addFileChildren(QaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRoute,
  EventsRoute: EventsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  QaRoute: QaRouteWithChildren,
  SignupRoute: SignupRoute,
  VideosRoute: VideosRoute,
  QuizCategoryRoute: QuizCategoryRoute,
  QuizBookmarksRoute: QuizBookmarksRoute,
  QuizLeaderboardRoute: QuizLeaderboardRoute,
  QuizMyAttemptsRoute: QuizMyAttemptsRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  QuizIndexRoute: QuizIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  QuizPlayQuizIdRoute: QuizPlayQuizIdRoute,
  QuizReviewAttemptIdRoute: QuizReviewAttemptIdRoute,
  ApiPublicHooksDispatchRemindersRoute: ApiPublicHooksDispatchRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
