/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as QaRouteImport } from './routes/qa'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizLeaderboardRouteImport } from './routes/quiz.leaderboard'
import { Route as QuizCategoryRouteImport } from './routes/quiz.$category'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as QuizPlayQuizIdRouteImport } from './routes/quiz.play.$quizId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRoute,
} as any)
const QuizLeaderboardRoute = QuizLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => QuizRoute,
} as any)
const QuizCategoryRoute = QuizCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => QuizRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const QuizPlayQuizIdRoute = QuizPlayQuizIdRouteImport.update({
  id: '/play/$quizId',
  path: '/play/$quizId',
  getParentRoute: () => QuizRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/qa': typeof QaRoute
  '/quiz': typeof QuizRouteWithChildren
  '/signup': typeof SignupRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/': typeof QuizIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/qa': typeof QaRoute
  '/signup': typeof SignupRoute
  '/videos': typeof VideosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz': typeof QuizIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRoute
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/qa': typeof QaRoute
  '/quiz': typeof QuizRouteWithChildren
  '/signup': typeof SignupRoute
  '/videos': typeof VideosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/': typeof QuizIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/events'
    | '/library'
    | '/login'
    | '/notices'
    | '/qa'
    | '/quiz'
    | '/signup'
    | '/videos'
    | '/admin'
    | '/profile'
    | '/quiz/$category'
    | '/quiz/leaderboard'
    | '/quiz/'
    | '/admin/users'
    | '/quiz/play/$quizId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/events'
    | '/library'
    | '/login'
    | '/notices'
    | '/qa'
    | '/signup'
    | '/videos'
    | '/profile'
    | '/quiz/$category'
    | '/quiz/leaderboard'
    | '/quiz'
    | '/admin/users'
    | '/quiz/play/$quizId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/events'
    | '/library'
    | '/login'
    | '/notices'
    | '/qa'
    | '/quiz'
    | '/signup'
    | '/videos'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/quiz/$category'
    | '/quiz/leaderboard'
    | '/quiz/'
    | '/_authenticated/admin/users'
    | '/quiz/play/$quizId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRoute
  EventsRoute: typeof EventsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  QaRoute: typeof QaRoute
  QuizRoute: typeof QuizRouteWithChildren
  SignupRoute: typeof SignupRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/leaderboard': {
      id: '/quiz/leaderboard'
      path: '/leaderboard'
      fullPath: '/quiz/leaderboard'
      preLoaderRoute: typeof QuizLeaderboardRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/$category': {
      id: '/quiz/$category'
      path: '/$category'
      fullPath: '/quiz/$category'
      preLoaderRoute: typeof QuizCategoryRouteImport
      parentRoute: typeof QuizRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/quiz/play/$quizId': {
      id: '/quiz/play/$quizId'
      path: '/play/$quizId'
      fullPath: '/quiz/play/$quizId'
      preLoaderRoute: typeof QuizPlayQuizIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface QuizRouteChildren {
  QuizCategoryRoute: typeof QuizCategoryRoute
  QuizLeaderboardRoute: typeof QuizLeaderboardRoute
  QuizIndexRoute: typeof QuizIndexRoute
  QuizPlayQuizIdRoute: typeof QuizPlayQuizIdRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizCategoryRoute: QuizCategoryRoute,
  QuizLeaderboardRoute: QuizLeaderboardRoute,
  QuizIndexRoute: QuizIndexRoute,
  QuizPlayQuizIdRoute: QuizPlayQuizIdRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRoute,
  EventsRoute: EventsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  QaRoute: QaRoute,
  QuizRoute: QuizRouteWithChildren,
  SignupRoute: SignupRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
