/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QaIndexRouteImport } from './routes/qa.index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as QuizMyAttemptsRouteImport } from './routes/quiz.my-attempts'
import { Route as QuizLeaderboardRouteImport } from './routes/quiz.leaderboard'
import { Route as QuizCategoryRouteImport } from './routes/quiz.$category'
import { Route as QaLeaderboardRouteImport } from './routes/qa.leaderboard'
import { Route as QaAskRouteImport } from './routes/qa.ask'
import { Route as QaQuestionIdRouteImport } from './routes/qa.$questionId'
import { Route as LibrarySubmitRouteImport } from './routes/library.submit'
import { Route as LibraryMySubmissionsRouteImport } from './routes/library.my-submissions'
import { Route as LibraryBookIdRouteImport } from './routes/library.$bookId'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as VideosWatchSlugRouteImport } from './routes/videos.watch.$slug'
import { Route as VideosPlaylistSlugRouteImport } from './routes/videos.playlist.$slug'
import { Route as VideosCategorySlugRouteImport } from './routes/videos.category.$slug'
import { Route as QuizReviewAttemptIdRouteImport } from './routes/quiz.review.$attemptId'
import { Route as QuizPlayQuizIdRouteImport } from './routes/quiz.play.$quizId'
import { Route as LibraryEditBookIdRouteImport } from './routes/library.edit.$bookId'
import { Route as EventsSlugLiveRouteImport } from './routes/events.$slug.live'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin.videos'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTournamentsRouteImport } from './routes/_authenticated/admin.tournaments'
import { Route as AuthenticatedAdminQaRouteImport } from './routes/_authenticated/admin.qa'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin.notices'
import { Route as AuthenticatedAdminLibraryRouteImport } from './routes/_authenticated/admin.library'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminQuizIndexRouteImport } from './routes/_authenticated/admin.quiz.index'
import { Route as ApiPublicHooksDispatchRemindersRouteImport } from './routes/api/public/hooks/dispatch-reminders'
import { Route as AuthenticatedAdminStageEventIdRouteImport } from './routes/_authenticated/admin.stage.$eventId'
import { Route as AuthenticatedAdminQuizCategoriesRouteImport } from './routes/_authenticated/admin.quiz.categories'
import { Route as AuthenticatedAdminQuizAttemptsRouteImport } from './routes/_authenticated/admin.quiz.attempts'
import { Route as AuthenticatedAdminQuizQuizIdRouteImport } from './routes/_authenticated/admin.quiz.$quizId'
import { Route as ApiPublicEventsSlugQrRouteImport } from './routes/api/public/events.$slug.qr'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/qa/',
  path: '/qa/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizMyAttemptsRoute = QuizMyAttemptsRouteImport.update({
  id: '/quiz/my-attempts',
  path: '/quiz/my-attempts',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizLeaderboardRoute = QuizLeaderboardRouteImport.update({
  id: '/quiz/leaderboard',
  path: '/quiz/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryRoute = QuizCategoryRouteImport.update({
  id: '/quiz/$category',
  path: '/quiz/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const QaLeaderboardRoute = QaLeaderboardRouteImport.update({
  id: '/qa/leaderboard',
  path: '/qa/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QaAskRoute = QaAskRouteImport.update({
  id: '/qa/ask',
  path: '/qa/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const QaQuestionIdRoute = QaQuestionIdRouteImport.update({
  id: '/qa/$questionId',
  path: '/qa/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySubmitRoute = LibrarySubmitRouteImport.update({
  id: '/library/submit',
  path: '/library/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMySubmissionsRoute = LibraryMySubmissionsRouteImport.update({
  id: '/library/my-submissions',
  path: '/library/my-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryBookIdRoute = LibraryBookIdRouteImport.update({
  id: '/library/$bookId',
  path: '/library/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const VideosWatchSlugRoute = VideosWatchSlugRouteImport.update({
  id: '/videos/watch/$slug',
  path: '/videos/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosPlaylistSlugRoute = VideosPlaylistSlugRouteImport.update({
  id: '/videos/playlist/$slug',
  path: '/videos/playlist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosCategorySlugRoute = VideosCategorySlugRouteImport.update({
  id: '/videos/category/$slug',
  path: '/videos/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizReviewAttemptIdRoute = QuizReviewAttemptIdRouteImport.update({
  id: '/quiz/review/$attemptId',
  path: '/quiz/review/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPlayQuizIdRoute = QuizPlayQuizIdRouteImport.update({
  id: '/quiz/play/$quizId',
  path: '/quiz/play/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryEditBookIdRoute = LibraryEditBookIdRouteImport.update({
  id: '/library/edit/$bookId',
  path: '/library/edit/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugLiveRoute = EventsSlugLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => EventsSlugRoute,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/blog/tag/$slug',
  path: '/blog/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTournamentsRoute =
  AuthenticatedAdminTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQaRoute = AuthenticatedAdminQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLibraryRoute =
  AuthenticatedAdminLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQuizIndexRoute =
  AuthenticatedAdminQuizIndexRouteImport.update({
    id: '/quiz/',
    path: '/quiz/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksDispatchRemindersRoute =
  ApiPublicHooksDispatchRemindersRouteImport.update({
    id: '/api/public/hooks/dispatch-reminders',
    path: '/api/public/hooks/dispatch-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminStageEventIdRoute =
  AuthenticatedAdminStageEventIdRouteImport.update({
    id: '/stage/$eventId',
    path: '/stage/$eventId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuizCategoriesRoute =
  AuthenticatedAdminQuizCategoriesRouteImport.update({
    id: '/quiz/categories',
    path: '/quiz/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuizAttemptsRoute =
  AuthenticatedAdminQuizAttemptsRouteImport.update({
    id: '/quiz/attempts',
    path: '/quiz/attempts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuizQuizIdRoute =
  AuthenticatedAdminQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicEventsSlugQrRoute = ApiPublicEventsSlugQrRouteImport.update({
  id: '/api/public/events/$slug/qr',
  path: '/api/public/events/$slug/qr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hadith': typeof HadithRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/quran': typeof QuranRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/library/$bookId': typeof LibraryBookIdRoute
  '/library/my-submissions': typeof LibraryMySubmissionsRoute
  '/library/submit': typeof LibrarySubmitRoute
  '/qa/$questionId': typeof QaQuestionIdRoute
  '/qa/ask': typeof QaAskRoute
  '/qa/leaderboard': typeof QaLeaderboardRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/my-attempts': typeof QuizMyAttemptsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/qa/': typeof QaIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/qa': typeof AuthenticatedAdminQaRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/events/$slug/live': typeof EventsSlugLiveRoute
  '/library/edit/$bookId': typeof LibraryEditBookIdRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/quiz/review/$attemptId': typeof QuizReviewAttemptIdRoute
  '/videos/category/$slug': typeof VideosCategorySlugRoute
  '/videos/playlist/$slug': typeof VideosPlaylistSlugRoute
  '/videos/watch/$slug': typeof VideosWatchSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/quiz/$quizId': typeof AuthenticatedAdminQuizQuizIdRoute
  '/admin/quiz/attempts': typeof AuthenticatedAdminQuizAttemptsRoute
  '/admin/quiz/categories': typeof AuthenticatedAdminQuizCategoriesRoute
  '/admin/stage/$eventId': typeof AuthenticatedAdminStageEventIdRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/admin/quiz/': typeof AuthenticatedAdminQuizIndexRoute
  '/api/public/events/$slug/qr': typeof ApiPublicEventsSlugQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hadith': typeof HadithRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/quran': typeof QuranRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/library/$bookId': typeof LibraryBookIdRoute
  '/library/my-submissions': typeof LibraryMySubmissionsRoute
  '/library/submit': typeof LibrarySubmitRoute
  '/qa/$questionId': typeof QaQuestionIdRoute
  '/qa/ask': typeof QaAskRoute
  '/qa/leaderboard': typeof QaLeaderboardRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/my-attempts': typeof QuizMyAttemptsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/blog': typeof BlogIndexRoute
  '/events': typeof EventsIndexRoute
  '/library': typeof LibraryIndexRoute
  '/qa': typeof QaIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/videos': typeof VideosIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/qa': typeof AuthenticatedAdminQaRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/events/$slug/live': typeof EventsSlugLiveRoute
  '/library/edit/$bookId': typeof LibraryEditBookIdRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/quiz/review/$attemptId': typeof QuizReviewAttemptIdRoute
  '/videos/category/$slug': typeof VideosCategorySlugRoute
  '/videos/playlist/$slug': typeof VideosPlaylistSlugRoute
  '/videos/watch/$slug': typeof VideosWatchSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/quiz/$quizId': typeof AuthenticatedAdminQuizQuizIdRoute
  '/admin/quiz/attempts': typeof AuthenticatedAdminQuizAttemptsRoute
  '/admin/quiz/categories': typeof AuthenticatedAdminQuizCategoriesRoute
  '/admin/stage/$eventId': typeof AuthenticatedAdminStageEventIdRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/admin/quiz': typeof AuthenticatedAdminQuizIndexRoute
  '/api/public/events/$slug/qr': typeof ApiPublicEventsSlugQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/hadith': typeof HadithRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/quran': typeof QuranRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/library/$bookId': typeof LibraryBookIdRoute
  '/library/my-submissions': typeof LibraryMySubmissionsRoute
  '/library/submit': typeof LibrarySubmitRoute
  '/qa/$questionId': typeof QaQuestionIdRoute
  '/qa/ask': typeof QaAskRoute
  '/qa/leaderboard': typeof QaLeaderboardRoute
  '/quiz/$category': typeof QuizCategoryRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/my-attempts': typeof QuizMyAttemptsRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/qa/': typeof QaIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/qa': typeof AuthenticatedAdminQaRoute
  '/_authenticated/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/events/$slug/live': typeof EventsSlugLiveRoute
  '/library/edit/$bookId': typeof LibraryEditBookIdRoute
  '/quiz/play/$quizId': typeof QuizPlayQuizIdRoute
  '/quiz/review/$attemptId': typeof QuizReviewAttemptIdRoute
  '/videos/category/$slug': typeof VideosCategorySlugRoute
  '/videos/playlist/$slug': typeof VideosPlaylistSlugRoute
  '/videos/watch/$slug': typeof VideosWatchSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/quiz/$quizId': typeof AuthenticatedAdminQuizQuizIdRoute
  '/_authenticated/admin/quiz/attempts': typeof AuthenticatedAdminQuizAttemptsRoute
  '/_authenticated/admin/quiz/categories': typeof AuthenticatedAdminQuizCategoriesRoute
  '/_authenticated/admin/stage/$eventId': typeof AuthenticatedAdminStageEventIdRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/_authenticated/admin/quiz/': typeof AuthenticatedAdminQuizIndexRoute
  '/api/public/events/$slug/qr': typeof ApiPublicEventsSlugQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hadith'
    | '/login'
    | '/notices'
    | '/quran'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/profile'
    | '/blog/$slug'
    | '/events/$slug'
    | '/library/$bookId'
    | '/library/my-submissions'
    | '/library/submit'
    | '/qa/$questionId'
    | '/qa/ask'
    | '/qa/leaderboard'
    | '/quiz/$category'
    | '/quiz/leaderboard'
    | '/quiz/my-attempts'
    | '/tournaments/$id'
    | '/blog/'
    | '/events/'
    | '/library/'
    | '/qa/'
    | '/quiz/'
    | '/tournaments/'
    | '/videos/'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/library'
    | '/admin/notices'
    | '/admin/qa'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/videos'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/events/$slug/live'
    | '/library/edit/$bookId'
    | '/quiz/play/$quizId'
    | '/quiz/review/$attemptId'
    | '/videos/category/$slug'
    | '/videos/playlist/$slug'
    | '/videos/watch/$slug'
    | '/admin/'
    | '/admin/quiz/$quizId'
    | '/admin/quiz/attempts'
    | '/admin/quiz/categories'
    | '/admin/stage/$eventId'
    | '/api/public/hooks/dispatch-reminders'
    | '/admin/quiz/'
    | '/api/public/events/$slug/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hadith'
    | '/login'
    | '/notices'
    | '/quran'
    | '/reset-password'
    | '/signup'
    | '/profile'
    | '/blog/$slug'
    | '/events/$slug'
    | '/library/$bookId'
    | '/library/my-submissions'
    | '/library/submit'
    | '/qa/$questionId'
    | '/qa/ask'
    | '/qa/leaderboard'
    | '/quiz/$category'
    | '/quiz/leaderboard'
    | '/quiz/my-attempts'
    | '/tournaments/$id'
    | '/blog'
    | '/events'
    | '/library'
    | '/qa'
    | '/quiz'
    | '/tournaments'
    | '/videos'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/library'
    | '/admin/notices'
    | '/admin/qa'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/videos'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/events/$slug/live'
    | '/library/edit/$bookId'
    | '/quiz/play/$quizId'
    | '/quiz/review/$attemptId'
    | '/videos/category/$slug'
    | '/videos/playlist/$slug'
    | '/videos/watch/$slug'
    | '/admin'
    | '/admin/quiz/$quizId'
    | '/admin/quiz/attempts'
    | '/admin/quiz/categories'
    | '/admin/stage/$eventId'
    | '/api/public/hooks/dispatch-reminders'
    | '/admin/quiz'
    | '/api/public/events/$slug/qr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/hadith'
    | '/login'
    | '/notices'
    | '/quran'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/blog/$slug'
    | '/events/$slug'
    | '/library/$bookId'
    | '/library/my-submissions'
    | '/library/submit'
    | '/qa/$questionId'
    | '/qa/ask'
    | '/qa/leaderboard'
    | '/quiz/$category'
    | '/quiz/leaderboard'
    | '/quiz/my-attempts'
    | '/tournaments/$id'
    | '/blog/'
    | '/events/'
    | '/library/'
    | '/qa/'
    | '/quiz/'
    | '/tournaments/'
    | '/videos/'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/library'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/qa'
    | '/_authenticated/admin/tournaments'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/videos'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/events/$slug/live'
    | '/library/edit/$bookId'
    | '/quiz/play/$quizId'
    | '/quiz/review/$attemptId'
    | '/videos/category/$slug'
    | '/videos/playlist/$slug'
    | '/videos/watch/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/quiz/$quizId'
    | '/_authenticated/admin/quiz/attempts'
    | '/_authenticated/admin/quiz/categories'
    | '/_authenticated/admin/stage/$eventId'
    | '/api/public/hooks/dispatch-reminders'
    | '/_authenticated/admin/quiz/'
    | '/api/public/events/$slug/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HadithRoute: typeof HadithRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  QuranRoute: typeof QuranRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
  LibraryBookIdRoute: typeof LibraryBookIdRoute
  LibraryMySubmissionsRoute: typeof LibraryMySubmissionsRoute
  LibrarySubmitRoute: typeof LibrarySubmitRoute
  QaQuestionIdRoute: typeof QaQuestionIdRoute
  QaAskRoute: typeof QaAskRoute
  QaLeaderboardRoute: typeof QaLeaderboardRoute
  QuizCategoryRoute: typeof QuizCategoryRoute
  QuizLeaderboardRoute: typeof QuizLeaderboardRoute
  QuizMyAttemptsRoute: typeof QuizMyAttemptsRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  QaIndexRoute: typeof QaIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
  LibraryEditBookIdRoute: typeof LibraryEditBookIdRoute
  QuizPlayQuizIdRoute: typeof QuizPlayQuizIdRoute
  QuizReviewAttemptIdRoute: typeof QuizReviewAttemptIdRoute
  VideosCategorySlugRoute: typeof VideosCategorySlugRoute
  VideosPlaylistSlugRoute: typeof VideosPlaylistSlugRoute
  VideosWatchSlugRoute: typeof VideosWatchSlugRoute
  ApiPublicHooksDispatchRemindersRoute: typeof ApiPublicHooksDispatchRemindersRoute
  ApiPublicEventsSlugQrRoute: typeof ApiPublicEventsSlugQrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/qa'
      fullPath: '/qa/'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/my-attempts': {
      id: '/quiz/my-attempts'
      path: '/quiz/my-attempts'
      fullPath: '/quiz/my-attempts'
      preLoaderRoute: typeof QuizMyAttemptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/leaderboard': {
      id: '/quiz/leaderboard'
      path: '/quiz/leaderboard'
      fullPath: '/quiz/leaderboard'
      preLoaderRoute: typeof QuizLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$category': {
      id: '/quiz/$category'
      path: '/quiz/$category'
      fullPath: '/quiz/$category'
      preLoaderRoute: typeof QuizCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/leaderboard': {
      id: '/qa/leaderboard'
      path: '/qa/leaderboard'
      fullPath: '/qa/leaderboard'
      preLoaderRoute: typeof QaLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/ask': {
      id: '/qa/ask'
      path: '/qa/ask'
      fullPath: '/qa/ask'
      preLoaderRoute: typeof QaAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/$questionId': {
      id: '/qa/$questionId'
      path: '/qa/$questionId'
      fullPath: '/qa/$questionId'
      preLoaderRoute: typeof QaQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/submit': {
      id: '/library/submit'
      path: '/library/submit'
      fullPath: '/library/submit'
      preLoaderRoute: typeof LibrarySubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/my-submissions': {
      id: '/library/my-submissions'
      path: '/library/my-submissions'
      fullPath: '/library/my-submissions'
      preLoaderRoute: typeof LibraryMySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$bookId': {
      id: '/library/$bookId'
      path: '/library/$bookId'
      fullPath: '/library/$bookId'
      preLoaderRoute: typeof LibraryBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/videos/watch/$slug': {
      id: '/videos/watch/$slug'
      path: '/videos/watch/$slug'
      fullPath: '/videos/watch/$slug'
      preLoaderRoute: typeof VideosWatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/playlist/$slug': {
      id: '/videos/playlist/$slug'
      path: '/videos/playlist/$slug'
      fullPath: '/videos/playlist/$slug'
      preLoaderRoute: typeof VideosPlaylistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/category/$slug': {
      id: '/videos/category/$slug'
      path: '/videos/category/$slug'
      fullPath: '/videos/category/$slug'
      preLoaderRoute: typeof VideosCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/review/$attemptId': {
      id: '/quiz/review/$attemptId'
      path: '/quiz/review/$attemptId'
      fullPath: '/quiz/review/$attemptId'
      preLoaderRoute: typeof QuizReviewAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/play/$quizId': {
      id: '/quiz/play/$quizId'
      path: '/quiz/play/$quizId'
      fullPath: '/quiz/play/$quizId'
      preLoaderRoute: typeof QuizPlayQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/edit/$bookId': {
      id: '/library/edit/$bookId'
      path: '/library/edit/$bookId'
      fullPath: '/library/edit/$bookId'
      preLoaderRoute: typeof LibraryEditBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/live': {
      id: '/events/$slug/live'
      path: '/live'
      fullPath: '/events/$slug/live'
      preLoaderRoute: typeof EventsSlugLiveRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/blog/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tournaments': {
      id: '/_authenticated/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qa': {
      id: '/_authenticated/admin/qa'
      path: '/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AuthenticatedAdminQaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/library': {
      id: '/_authenticated/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AuthenticatedAdminLibraryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz/': {
      id: '/_authenticated/admin/quiz/'
      path: '/quiz'
      fullPath: '/admin/quiz/'
      preLoaderRoute: typeof AuthenticatedAdminQuizIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/dispatch-reminders': {
      id: '/api/public/hooks/dispatch-reminders'
      path: '/api/public/hooks/dispatch-reminders'
      fullPath: '/api/public/hooks/dispatch-reminders'
      preLoaderRoute: typeof ApiPublicHooksDispatchRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/stage/$eventId': {
      id: '/_authenticated/admin/stage/$eventId'
      path: '/stage/$eventId'
      fullPath: '/admin/stage/$eventId'
      preLoaderRoute: typeof AuthenticatedAdminStageEventIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz/categories': {
      id: '/_authenticated/admin/quiz/categories'
      path: '/quiz/categories'
      fullPath: '/admin/quiz/categories'
      preLoaderRoute: typeof AuthenticatedAdminQuizCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz/attempts': {
      id: '/_authenticated/admin/quiz/attempts'
      path: '/quiz/attempts'
      fullPath: '/admin/quiz/attempts'
      preLoaderRoute: typeof AuthenticatedAdminQuizAttemptsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz/$quizId': {
      id: '/_authenticated/admin/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/admin/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedAdminQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/events/$slug/qr': {
      id: '/api/public/events/$slug/qr'
      path: '/api/public/events/$slug/qr'
      fullPath: '/api/public/events/$slug/qr'
      preLoaderRoute: typeof ApiPublicEventsSlugQrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminLibraryRoute: typeof AuthenticatedAdminLibraryRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminQaRoute: typeof AuthenticatedAdminQaRoute
  AuthenticatedAdminTournamentsRoute: typeof AuthenticatedAdminTournamentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminQuizQuizIdRoute: typeof AuthenticatedAdminQuizQuizIdRoute
  AuthenticatedAdminQuizAttemptsRoute: typeof AuthenticatedAdminQuizAttemptsRoute
  AuthenticatedAdminQuizCategoriesRoute: typeof AuthenticatedAdminQuizCategoriesRoute
  AuthenticatedAdminStageEventIdRoute: typeof AuthenticatedAdminStageEventIdRoute
  AuthenticatedAdminQuizIndexRoute: typeof AuthenticatedAdminQuizIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminLibraryRoute: AuthenticatedAdminLibraryRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminQaRoute: AuthenticatedAdminQaRoute,
  AuthenticatedAdminTournamentsRoute: AuthenticatedAdminTournamentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminQuizQuizIdRoute: AuthenticatedAdminQuizQuizIdRoute,
  AuthenticatedAdminQuizAttemptsRoute: AuthenticatedAdminQuizAttemptsRoute,
  AuthenticatedAdminQuizCategoriesRoute: AuthenticatedAdminQuizCategoriesRoute,
  AuthenticatedAdminStageEventIdRoute: AuthenticatedAdminStageEventIdRoute,
  AuthenticatedAdminQuizIndexRoute: AuthenticatedAdminQuizIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EventsSlugRouteChildren {
  EventsSlugLiveRoute: typeof EventsSlugLiveRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugLiveRoute: EventsSlugLiveRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HadithRoute: HadithRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  QuranRoute: QuranRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  EventsSlugRoute: EventsSlugRouteWithChildren,
  LibraryBookIdRoute: LibraryBookIdRoute,
  LibraryMySubmissionsRoute: LibraryMySubmissionsRoute,
  LibrarySubmitRoute: LibrarySubmitRoute,
  QaQuestionIdRoute: QaQuestionIdRoute,
  QaAskRoute: QaAskRoute,
  QaLeaderboardRoute: QaLeaderboardRoute,
  QuizCategoryRoute: QuizCategoryRoute,
  QuizLeaderboardRoute: QuizLeaderboardRoute,
  QuizMyAttemptsRoute: QuizMyAttemptsRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  QaIndexRoute: QaIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
  LibraryEditBookIdRoute: LibraryEditBookIdRoute,
  QuizPlayQuizIdRoute: QuizPlayQuizIdRoute,
  QuizReviewAttemptIdRoute: QuizReviewAttemptIdRoute,
  VideosCategorySlugRoute: VideosCategorySlugRoute,
  VideosPlaylistSlugRoute: VideosPlaylistSlugRoute,
  VideosWatchSlugRoute: VideosWatchSlugRoute,
  ApiPublicHooksDispatchRemindersRoute: ApiPublicHooksDispatchRemindersRoute,
  ApiPublicEventsSlugQrRoute: ApiPublicEventsSlugQrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
